edit_uri: edit/main/docs/
extra:
  generator: false
  swagger_url: https://petstore.swagger.io/v2/swagger.json
extra_css:
- css/truncate.css
- https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- https://code.jquery.com/jquery-3.5.1.js
- https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js
- js/tables.js
- https://cdn.datatables.net/plug-ins/1.11.3/dataRender/ellipsis.js
markdown_extensions:
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.tasklist
- footnotes
- attr_list
- pymdownx.snippets
- pymdownx.highlight
- pymdownx.superfences
nav:
- Home: index.md
- Dictionary: dictionary.md
- Datasets:
    Annual Output: datasets/annual-output.md
    BMU Fuel Types: datasets/bmu-fuel-types.md
    Carbon Intensity: datasets/carbon-intensity.md
    CfD Contract Portfolio Status: datasets/cfd-contract-portfolio-status.md
    CfD Strike Prices: datasets/cfd-strike-prices.md
    EU Transation Lag: datasets/eutl.md
    EUTL Verified Emissions: datasets/verified-emissions.md
    Global Power Plant Database: datasets/global-power-plant-database.md
    Load Factors: datasets/load-factors.md
    Nuclear Power Plants Database: datasets/nuclear-power-plants.md
    Power Plant Capture Prices: datasets/capture-prices.md
    Power Plant Common Names: datasets/common-names.md
    Power Plant Locations: datasets/plant-locations.md
    Renewable Energy Planning Database: datasets/renewable-energy-planning-database.md
    Wind Farms: datasets/wind-farms.md
    jrc-hydro-power-plants-database: datasets/jrc-hydro-power-plants-database.md
- Sites:
  - AChruach Wind Farm: objects/10147.md
  - Aberdare District Energy: objects/10078.md
  - Aberdeen Bay: objects/10294.md
  - Aberthaw B: objects/10002.md
  - Achlachan: objects/10288.md
  - Afton: objects/10295.md
  - Aikengall 2 Wind Farm Generation: objects/10148.md
  - Airies Windfarm: objects/10149.md
  - Aldershot Military Generator: objects/10077.md
  - An Suidhe Windfarm: objects/10151.md
  - Andershaw Wind Farm: objects/10150.md
  - Arecleoch Windfarm: objects/10152.md
  - Assel Valley Wind Farm: objects/10153.md
  - Auchrobert Wind Farm: objects/10154.md
  - Bad a Cheo: objects/10296.md
  - Baglan Bay: objects/10021.md
  - Baillie Wind Farm: objects/10155.md
  - Barking 2 MGT: objects/10022.md
  - Barrow Offshore Windfarm: objects/10156.md
  - Barry: objects/10024.md
  - Beatrice: objects/10297.md
  - Beauly Cascade: objects/10107.md
  - Beinn An Tuirc 2 Windfarm: objects/10157.md
  - Beinn Tharsuinn: objects/10159.md
  - Beinneun Wind Farm: objects/10158.md
  - Bentinck: objects/10079.md
  - Berkeley: objects/10312.md
  - Berry Burn Windfarm: objects/10160.md
  - Bhlaraidh Windfarm 1: objects/10161.md
  - Black Law Wind Farm: objects/10163.md
  - Blackcraig Windfarm: objects/10162.md
  - Bloxwich: objects/10274.md
  - Blyth Offshore Demonstrator Windfarm Generation: objects/10165.md
  - Bradwell: objects/10127.md
  - Braes of Doune: objects/10166.md
  - Bridgewater District Energy: objects/10080.md
  - Brigg: objects/10026.md
  - Brockloch Rig 2 Windfarm: objects/10167.md
  - Brownieleys Windfarm: objects/10168.md
  - Burbo Bank Offshore Windfarm: objects/10169.md
  - Burn of Whilk Windfarm: objects/10171.md
  - Cairn Uish - Rothes Windfarm Extension: objects/10172.md
  - Calder: objects/10313.md
  - Camster Wind Farm: objects/10173.md
  - Carnegie Road: objects/10278.md
  - Carraig Gheal Wind Farm: objects/10174.md
  - Carrington: objects/10027.md
  - Castleford CCGT: objects/10028.md
  - Caythorpe: objects/10081.md
  - Clachan Flats Windfarm: objects/10175.md
  - Clachan Power Station: objects/10108.md
  - Clashindarroch Wind Farm: objects/10176.md
  - Clunie Cascade: objects/10109.md
  - Clyde Central Windfarm, Clyde North Windfarm, Clyde South Windfarm: objects/10177.md
  - Cockenzie: objects/10015.md
  - Coire Na Cloiche: objects/10289.md
  - Connahs Quay: objects/10029.md
  - Conon Cascade: objects/10110.md
  - Corby: objects/10030.md
  - Corriegarth Wind Farm: objects/10178.md
  - Corriemoillie Wind Farm: objects/10179.md
  - Coryton: objects/10031.md
  - Cottam: objects/10003.md
  - Cottam Development Centre Limited: objects/10032.md
  - Cour Wind Farm: objects/10180.md
  - Cowes: objects/10091.md
  - Craig 2: objects/10277.md
  - Crauchan: objects/10143.md
  - Crossdykes: objects/10298.md
  - Crystal Rig Wind Farm: objects/10181.md
  - Cwm Dyli: objects/10111.md
  - Dalswinton Wind Farm: objects/10183.md
  - Damhead Creek: objects/10033.md
  - Deeside: objects/10034.md
  - Dersalloch Windfarm: objects/10184.md
  - Derwent: objects/10064.md
  - Didcot: objects/10001.md
  - Dinorwig: objects/10144.md
  - Dolgarrog: objects/10112.md
  - Dorenell: objects/10299.md
  - Dounreay: objects/10314.md
  - Drakelow: objects/10016.md
  - Drax: objects/10004.md
  - Dudgeon Offshore Wind Farm Generator: objects/10185.md
  - Dun Law Extension Windfarm: objects/10186.md
  - Dungeness B: objects/10128.md
  - Dunmglass Wind Farm: objects/10187.md
  - East Anglia: objects/10300.md
  - Edinbane Windfarm: objects/10188.md
  - Eggborough: objects/10005.md
  - Enfield Energy: objects/10036.md
  - Errochty G: objects/10115.md
  - Ewe Hill II Wind Farm: objects/10189.md
  - Fallago Rig Wind Farm: objects/10190.md
  - Farr Wind Farm: objects/10191.md
  - Fasnakyle G: objects/10116.md
  - Fawley: objects/10082.md
  - Fawley Cogen: objects/10065.md
  - Fellside: objects/10066.md
  - Ferrybridge C: objects/10006.md
  - Ffestiniog: objects/10145.md
  - Fibropower: objects/10142.md
  - Fiddlers Ferry: objects/10007.md
  - Fife CCGT: objects/10037.md
  - Fifoots: objects/10008.md
  - Finlarig: objects/10117.md
  - Fort Dunlop: objects/10083.md
  - Foyers G: objects/10146.md
  - Freasdail Wind Farm: objects/10192.md
  - Galawhistle Wind Farm: objects/10193.md
  - Galloper Offshore Windfarm 1: objects/10194.md
  - Garry Cascade: objects/10118.md
  - Glen App Wind Farm: objects/10195.md
  - Glenchamber Wind Farm: objects/10196.md
  - Glendoe: objects/10119.md
  - Glens of Foudland: objects/10197.md
  - Goole Fields 1 Windfarm: objects/10198.md
  - Gordonbush Wind Farm: objects/10199.md
  - Gordonstown Windfarm: objects/10200.md
  - Grain: objects/10067.md
  - Grangemouth CHP Ltd: objects/10068.md
  - Great Yarmouth: objects/10038.md
  - Greater Gabbard Offshore Windfarm: objects/10201.md
  - Griffin Wind Farm: objects/10202.md
  - Gunfleet Sands Windfarm: objects/10204.md
  - Gwynt y Mor Offshore Wind Farm: objects/10206.md
  - Hadyard Hill Wind Farm: objects/10208.md
  - Halsary: objects/10293.md
  - Harburnhead Wind Farm: objects/10209.md
  - Hare Hill Extension Wind Farm: objects/10210.md
  - Harestanes Windfarm: objects/10211.md
  - Hartlepool: objects/10130.md
  - Heysham: objects/10131.md
  - High Marnham: objects/10017.md
  - Hill of Glaschyle Windfarm: objects/10212.md
  - Hill of Towie Windfarm: objects/10213.md
  - Hinkley Point B: objects/10133.md
  - Hornsea: objects/10301.md
  - Humber Offshore Wind Farm: objects/10214.md
  - Hunterston Generator: objects/10134.md
  - Hywind Generator 1: objects/10215.md
  - Immingham CHP: objects/10070.md
  - Indian Queens: objects/10097.md
  - Ironbridge B: objects/10018.md
  - Keadby: objects/10039.md
  - Keith Hill Windfarm: objects/10216.md
  - Kilbraur Windfarm: objects/10217.md
  - Kilgallioch Wind Farm: objects/10218.md
  - Killin Cascade: objects/10120.md
  - Killingholme: objects/10040.md
  - Kincardine: objects/10290.md
  - Kings Lynn: objects/10042.md
  - Kingsnorth: objects/10019.md
  - Kype Muir: objects/10302.md
  - Langage: objects/10043.md
  - Letchworth: objects/10279.md
  - Lincs Offshore Wind Farm: objects/10219.md
  - Little Barford: objects/10044.md
  - Littlebrook D: objects/10141.md
  - Lochluichart Windfarm: objects/10220.md
  - London Array Windfarm: objects/10221.md
  - Longannet: objects/10009.md
  - Lynemouth Generator: objects/10010.md
  - Maentwrog: objects/10121.md
  - Marchwood: objects/10045.md
  - Mark Hill Windfarm: objects/10222.md
  - Medway: objects/10046.md
  - Mid Hill Windfarm: objects/10223.md
  - Middle Muir: objects/10303.md
  - Millennium Wind Farm: objects/10224.md
  - Minnygap Wind Farm: objects/10225.md
  - Minsca Wind Farm: objects/10226.md
  - Moray East: objects/10304.md
  - Moriston Cascade: objects/10122.md
  - Moy Windfarm: objects/10227.md
  - Nant: objects/10123.md
  - Oldbury: objects/10135.md
  - Ormonde Windfarm: objects/10229.md
  - Pauls Hill Windfarm: objects/10231.md
  - Pembroke Power Station -: objects/10047.md
  - Pen y Cymoedd Wind Farm: objects/10232.md
  - Peterborough: objects/10048.md
  - Peterhead: objects/10101.md
  - Pogbie: objects/10305.md
  - Pye Bridge: objects/10086.md
  - Race Bank Offshore Wind Farm: objects/10233.md
  - Rampion Offshore Windfarm: objects/10234.md
  - Ratcliffe on Soar: objects/10011.md
  - Redditch: objects/10087.md
  - Rheidol: objects/10124.md
  - Robin Rigg: objects/10235.md
  - Rocksavage: objects/10049.md
  - Roosecote: objects/10050.md
  - Rosehall: objects/10291.md
  - Rothes (Cairn Uish) Wind Farm: objects/10237.md
  - Rothes Bio-Plant CHP: objects/10000.md
  - Rugeley B: objects/10012.md
  - Rye House: objects/10051.md
  - Saltend South: objects/10052.md
  - Sandbach CHP: objects/10071.md
  - Sanquhar Community Wind Farm Generation: objects/10238.md
  - Seabank: objects/10053.md
  - Severn Power: objects/10054.md
  - Sevington District Energy: objects/10088.md
  - Sheringham Shoals Windfarm: objects/10239.md
  - Shoreham: objects/10055.md
  - Shotton CHP: objects/10072.md
  - Sizewell: objects/10136.md
  - Slough: objects/10073.md
  - Sloy G: objects/10125.md
  - Solutia District Energy: objects/10089.md
  - South Humber Bank: objects/10056.md
  - Spalding: objects/10057.md
  - Staythorpe: objects/10058.md
  - Stoke CHP: objects/10074.md
  - Strathy North Wind Farm 1: objects/10240.md
  - Stronelairg Windfarm: objects/10284.md
  - Sutton Bridge: objects/10059.md
  - Taylors Lane: objects/10104.md
  - Teesside: objects/10060.md
  - Thanet Offshore Windfarm: objects/10242.md
  - Thornhill CCGT: objects/10061.md
  - Tilbury B: objects/10020.md
  - Toddleburn Wind Farm: objects/10243.md
  - Torness Generator: objects/10138.md
  - Tralorg: objects/10307.md
  - Trawsfynydd: objects/10315.md
  - Triton Knoll: objects/10306.md
  - Tullo: objects/10244.md
  - Tullymurdoch: objects/10292.md
  - Twenty Shillings: objects/10308.md
  - Uskmouth: objects/10013.md
  - Walney Offshore Windfarm: objects/10246.md
  - Wathegar: objects/10311.md
  - Weaver Power Station: objects/10075.md
  - West Burton: objects/10014.md
  - West of Duddon Sands: objects/10250.md
  - Westermost Rough Windfarm: objects/10248.md
  - Weston Point Power Station: objects/10076.md
  - Whitelee Wind Farm: objects/10252.md
  - Whiteside Hill: objects/10310.md
  - Windscale: objects/10316.md
  - Windy Rig: objects/10309.md
  - Winfrith: objects/10317.md
  - Wylfa: objects/10139.md
  - 10063: objects/10063.md
- Use Cases:
  - use-cases/carbon-intensity.md
plugins:
- search
- swagger
repo_name: Power-Station-Dictionary
repo_url: https://github.com/OSUKED/Power-Station-Dictionary
site_name: Power-Station-Dictionary
theme:
  features:
  - header.autohide
  - navigation.tabs
  - navigation.instant
  - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    primary: black
